from pathlib import Path
import json

repo = 'organvm/peer-audited--behavioral-blockchain'
base = f'https://github.com/{repo}'
entries = {}


def distilled(n, evidence, finding, next_step):
    entries[n] = {
        'new_disposition': 'distilled',
        'body': f"I re-read this against current HEAD and checked {evidence}. {finding} The most useful continuation now is {next_step}, so I’m treating the issue as a distillation target rather than a blank-slate request."
    }


def evolving(n, evidence, finding, next_step):
    entries[n] = {
        'new_disposition': 'evolving',
        'body': f"I checked current HEAD at {evidence}. {finding} The remaining work is concrete now: {next_step}."
    }


def engaged(n, evidence, finding, blocker):
    entries[n] = {
        'new_disposition': 'engaged',
        'body': f"I checked {evidence}. {finding} This is still materially open because {blocker}, so I’m keeping it engaged instead of pretending it is resolved."
    }


def superseded(n, url, evidence, finding):
    entries[n] = {
        'new_disposition': f'superseded:{url}',
        'body': f"I checked current HEAD and the requested change is already present in {evidence}. {finding} The concrete ask now reads as superseded by {url}, while the issue remains useful as lineage."
    }

# 226-236 audit/doc cluster

distilled(226, '`src/api/src/modules/`, `docs/planning/evaluation-to-growth--architecture-corpus--2026-05-16.md`, and `docs/planning/feature-matrix.md`', 'The repo already exposes the big module families (auth, contracts, fury, wallet, compliance, B2B), but the unresolved value here is the fine-grained controller/service/provider map and endpoint count per module.', 'a canonical module matrix that ties each NestJS module to routes, injected dependencies, and verification coverage')
distilled(227, '`src/shared/libs/`, `src/shared/behavioral-physics/`, and `src/shared/fury-logic/`', 'There is already substantial shared surface area, so the risk is drift between utility exports, domain algorithms, and what downstream packages actually import.', 'a single inventory of export signatures plus ownership boundaries for money/integrity/behavioral logic')
distilled(228, '`src/web/app/`, `src/web/components/`, `src/web/store/`, and `src/web/services/`', 'The route tree is real (`dashboard`, `fury`, `wallet`, `legal`, `hr`, etc.), but the audit still needs to connect pages/components/stores back to their API dependencies instead of just listing folders.', 'a route-to-component-to-API map that makes frontend completeness measurable')
distilled(229, '`src/mobile/screens/`, `src/mobile/services/`, and the native iOS/Android folders under `src/mobile/`', 'The mobile codebase is present, but the useful split is between truly wired flows and screens that are still scaffold-level or blocked by native dependencies.', 'an implementation inventory that separates working RN screens from HealthKit/secure-camera/native-bridge gaps')
distilled(230, '`src/desktop/src/components/`, `src/desktop/src/services/`, and `src/desktop/src-tauri/`', 'The Judge desktop surface is no longer hypothetical; there are concrete panels, but completeness still depends on which admin actions are actually wired end to end.', 'a panel-by-panel audit that pairs each desktop surface with the backing API/service path and missing operator actions')
distilled(231, '`src/api/database/schema.sql` plus migrations like `010_settlements_and_jurisdictions.sql`, `011_fury_audit_masks.sql`, `015_cross_lobby_auditing_fields.sql`, and `020_phase_gamma_trust_chain.sql`', 'The schema footprint is large enough now that a useful audit is not “does SQL exist?” but “which tables/columns/constraints implement which feature promises?”', 'a normalized schema report mapping tables and constraints to feature/ticket ownership')
distilled(232, '`docs/planning/planning--alpha-omega-completion-matrix.md`, `docs/planning/feature-matrix.md`, and `docs/FEATURE-BACKLOG.md`', 'There are already multiple completeness views, so the real work is reconciling disagreements between them rather than creating yet another percentage table.', 'one authoritative completeness matrix with explicit status rules and source-of-truth precedence')
distilled(233, '`docs/planning/planning--alpha-omega-completion-matrix.md`, `docs/planning/feature-matrix.md`, and `docs/planning/implementation-status.md`', 'The ingredients for the report already exist; what is missing is a single publishable narrative that collapses those matrices into one audited artifact.', 'one report that names the authoritative matrix and records where current status claims still conflict')
distilled(234, '`docs/specs/spec--fury-router.md`, `docs/specs/spec--digital-exhaust-intake.md`, `docs/architecture/architecture--alpha-to-omega-plan.md`, `docs/architecture/architecture--feasibility-stack.md`, `docs/architecture/architecture--technical-feasibility.md`, `docs/architecture/architecture--truth-blockchain-v2.md`, and `docs/architecture/architecture--aegis-tier-reconciliation.md`', 'Most of the named architecture artifacts now exist, but they span `docs/specs/` and `docs/architecture/` with some naming drift from the issue text.', 'a reconciled extraction pass that cites the current filenames and flags any concept that still lacks a living home')
distilled(235, '`git log` at current HEAD (recently `#787`, `#771`, `#779`, `#751`, `#750`) plus the existing audit/planning artifacts', 'Raw commit retrieval is easy now; the lasting value is interpreting the recent sequence as dependency maintenance, CI repair, and operational stabilization rather than dumping hashes.', 'a concise trend summary tying recent commits to repo direction and remaining risk')
distilled(236, '`docs/planning/2026-03-05-evaluation-to-growth-final-report.md` and `docs/planning/evaluation-to-growth--full-breath-audit--2026-03-06.md`', 'A “final summary” already exists in multiple forms, which means the live problem is not absence but reconciliation against today’s repository state.', 'one maintained audit summary that explicitly states what those earlier reports got right, what has since moved, and what remains open')

# 237-255 governance/doc-intel cluster
engaged(237, 'current repo tree and the issue-targeted path `meta-organvm/organvm-corpvs-testamentvm/registry-v2.json`', 'I do not see that registry file vendored in this repository, so this ask is clearly cross-repo governance work rather than a local Styx code change.', 'the authoritative file lives outside this checkout and needs a cross-repo governance sync, not guesswork from within this repo')
superseded(238, f'{base}/commit/5aa2cd617991024923b7e23e441d17b8231ec788', '`seed.yaml` (`metadata.tier: flagship`) and its history', 'The tier is already `flagship` at current HEAD, and the historical landing point for that promotion is visible in the seed history.')
engaged(239, 'this repo plus the referenced external path `meta-organvm/organvm-corpvs-testamentvm/docs/standards/`', 'The Styx repo now has strong local governance docs (`AGENTS.md`, `CLAUDE.md`, department `REGE.md`s), but not the cross-repo habitat standard file named here.', 'the standard belongs to the external governance corpus, so the remaining work is authoring there and then linking back here')
distilled(240, '`README.md`, `docs/README.md`, `docs/departments/README.md`, and `seed.yaml`', 'The topology information is already spread across repo/workspace/department/governance docs, which makes this less a missing idea than a missing synthesized diagram.', 'one topology artifact that shows repo layer, organ layer, and orchestration layer without duplicating scattered prose')
engaged(241, 'the repo plus the command references `organvm registry validate`, `organvm metrics calculate`, and `organvm seed validate`', 'The sync intent is clear, but those commands depend on the wider `organvm` toolchain rather than something I can prove from this checkout alone.', 'the validation surface is external to this repo, so the issue remains a live governance/CLI sync task')
superseded(245, f'{base}/commit/fc557887d7b7c1325134a80f8926ec7e1a73c7b2', '`.github/workflows/ci.yml`, `package.json` (`beta:readiness`), `scripts/smoke/beta-readiness.sh`, and `docs/planning/planning--beta-readiness-contract.md`', 'Beta readiness is already wired into CI and the README documents the artifact upload path, so the specific “integrate the gate” ask has landed in code.')
distilled(246, '`scripts/analysis/ingest-doc-intelligence.js`, `docs/planning/planning--doc-ingest-register.md`, and the existing planning/audit corpus', 'A doc-intelligence substrate already exists in practice, so the open value is not directory creation by itself but making the pipeline boundaries explicit.', 'a clearly owned doc-intelligence workspace with ingestion, extraction, classification, and ticketing stages separated')
distilled(247, '`scripts/analysis/ingest-doc-intelligence.js` and `docs/planning/planning--doc-ingest-register.md`', 'The repo already tracks doc-ingest metadata, which means the issue should now harden the inventory contract (hash, size, first/last seen, source provenance) instead of just proving inventory is possible.', 'a deterministic inventory artifact with stable columns and rerunnable generation')
distilled(248, '`docs/planning/planning--research-ticket-pack--2026-03-04.md`, `docs/FEATURE-BACKLOG.md`, and the existing planning corpus', 'Atomic extraction is already happening informally through ticket packs and backlog normalization, but it is not yet framed as one explicit extraction pass.', 'an extraction step that emits claims/requirements/definitions into a stable intermediate format before synthesis')
distilled(249, '`docs/planning/planning--unity-contention-register--2026-03-04.md` and `scripts/analysis/ingest-doc-intelligence.js`', 'Unity/contention classification already has an artifact, so the useful continuation is formalizing how contradictions are detected and routed instead of rewriting the register.', 'a classifier contract that explains why an item is “unity” vs “contention” and where the fix should land')
distilled(250, '`docs/research/competitors/`-style deep dives already present under `docs/research/` (Beeminder, Habitica, StickK, Focusmate, Pavlok, WayBetter, etc.)', 'The competitor corpus is substantial now, so the enduring question is feature-gap synthesis rather than raw parsing.', 'a gap table that maps each competitor insight to concrete Styx differentiators or missing capabilities')
distilled(251, '`docs/planning/planning--research-ticket-pack--2026-03-04.md` and the ticket-oriented sections in `docs/FEATURE-BACKLOG.md`', 'Implementation-ready ticket structure already exists in prose, but it is not yet normalized into one repeatable template with API/schema/test sections.', 'a strict ticket template that always captures routes, schema diffs, invariants, and acceptance tests')
distilled(252, '`docs/planning/planning--doc-ingest-register.md` plus the various planning gap/matrix artifacts', 'There is enough registry material now that cross-referencing gaps is a reconciliation problem, not a discovery problem.', 'a joined view that traces each named gap back to the doc-ingest register entry that produced it')
distilled(253, '`docs/pitch/pitch--styx-deck.pptx`, `docs/pitch/content.md`, and the investor-facing narrative in `README.md`', 'An investor deck already exists, so this issue is best used to keep the deck aligned with the current product/compliance story rather than to start from zero.', 'a maintained investor deck spec that calls out what still needs refresh before external use')
engaged(254, '`docs/pitch/`, `docs/finance/`, and the current docs tree', 'I found investor-facing material and finance docs, but not a clearly canonical standalone 2–3 page executive-summary PDF artifact called out as such.', 'the repo has adjacent material, but the exact distribution-form artifact still needs to be defined and generated')
distilled(255, '`docs/legal/regulatory-risk-register.md`, `docs/legal/legal--real-money-activation-brief.md`, `docs/finance/runway-tracker.md`, and `docs/finance/financial-projections.md`', 'Risk and resourcing are both already documented, just in separate homes.', 'one synthesis layer that ties legal/operational/financial risk to staffing and spend decisions instead of leaving them in parallel documents')

distilled(259, '`docs/planning/2026-03-05-evaluation-to-growth-final-report.md`, `docs/planning/evaluation-to-growth--full-breath-audit--2026-03-06.md`, `docs/planning/evaluation-to-growth--architecture-corpus--2026-05-16.md`, and related E2G artifacts', 'The overlap problem is real because multiple E2G-era documents now coexist with similar scope but different status claims.', 'an overlap map that records which E2G artifact is canonical for which decision surface')
distilled(260, '`docs/planning/planning--implementation-status.md`, `docs/planning/planning--alpha-omega-completion-matrix.md`, and `docs/FEATURE-BACKLOG.md`', 'A canonical status matrix is still valuable, but only if it declares precedence between these already-existing status surfaces.', 'one status ledger that maps each suggestion/feature to exactly one current truth source')
engaged(265, 'the tracked tree plus a direct scan for obvious temp/cache patterns (`*.tmp`, `*.bak`, `*tool*output*`, `.DS_Store`) and current `git status`', 'Current HEAD scanned clean for those obvious ephemeral artifacts, so the issue has shifted from emergency cleanup to defining what counts as ephemeral cache vs. legitimate generated artifact.', 'the repo does not currently expose the claimed junk locally, so the next step is codifying the audit criteria before deleting anything')
distilled(267, '`docs/departments/README.md`, the eight department `REGE.md` files, `PULSE.md`, and the repo-level agent charters', 'The domain-expert context system is already partially alive in the department organisms.', 'an epic tracker that explicitly maps each agent context to its inputs, outputs, CRIT/HEAL loops, and owner surfaces')
distilled(268, '`docs/enterprise/icp.md`, `docs/departments/b2b/REGE.md`, and `docs/enterprise/outreach-sequences.md`', 'The ICP work is no longer absent; the sharper need is keeping firmographics, buying triggers, and segment-specific messaging synchronized across sales artifacts.', 'one canonical ICP owner doc with downstream references rather than parallel copies')
distilled(269, '`docs/finance/unit-economics.md`, `docs/finance/financial-projections.md`, and `docs/finance/pricing-strategy.md`', 'The unit-economics model now has a home, so the live question is maintaining assumptions and break-even logic against actual pricing/escrow mechanics.', 'a single source of truth for contract economics and the assumptions that feed it')
distilled(270, '`docs/marketing/seo-strategy.md`, `docs/marketing/gtm-strategy.md`, and the no-contact planning docs', 'SEO strategy already exists, which means this issue is best used to keep the keyword map tied to the actual wedge and content plan.', 'an explicit keyword-to-article-to-conversion-path matrix for the no-contact niche')
distilled(271, '`docs/legal/legal--app-store-ugc-moderation-packet.md` plus the App Review notes and appendices', 'The moderation policy artifact already exists in substantive form, including TestFlight vs public-launch gates.', 'keeping the checklist executable and linked to concrete moderation/reporting surfaces rather than rewriting the policy from scratch')
distilled(272, '`docs/operations/incident-response.md`, `docs/operations/monitoring-setup.md`, and the operations REGE artifacts', 'There is already a runbook base here, so the remaining value is making incident roles, rollback paths, and alert thresholds operationally crisp.', 'a maintained incident playbook tied to actual monitors and escalation owners')
distilled(273, '`docs/planning/ux-audit.md`, the route tree under `src/web/app/`, and the mobile/web proof flows', 'A UX audit artifact already exists, but its usefulness depends on grounding findings in the five named critical flows rather than generic product critique.', 'a flow-by-flow friction/safety/a11y audit with evidence traces into the actual UI paths')
distilled(274, '`docs/customer-success/faq.md`, `docs/customer-success/onboarding-sequence.md`, and the linguistic-cloaker/legal surfaces', 'FAQ/help content already has a home.', 'keeping the article set aligned with the cloaker vocabulary, policy surfaces, and current onboarding reality')

# 278-305 product/department/readiness cluster

evolving(278, '`src/api/database/migrations/010_settlements_and_jurisdictions.sql`, `README.md` (`GEOFENCE_FAIL_OPEN_ON_MISSING_HEADERS`), and the compliance/legal docs', 'The repo already has jurisdiction tables and planning artifacts, but the public env contract still documents a fail-open fallback when geo headers are missing.', 'wire every contest-entry path to a single fail-closed decision source, expose the policy introspection surface, and test ambiguous-header / VPN / no-location behavior explicitly')
evolving(279, '`src/api/database/migrations/010_settlements_and_jurisdictions.sql` plus the legal/planning references for `TKT-P0-011`', 'Disposition modes are already visible in schema/planning, so the open seam is runtime policy enforcement rather than data modeling alone.', 'implement the per-jurisdiction decision engine, add the refund-only global override, and prove settlement behavior under state-policy changes')
evolving(280, '`src/api/services/security/self-exclusion.service.ts`, `/src/web/app/legal/responsible-use/page.tsx`, and the planning references for `self_exclusions`', 'Responsible-use surfaces exist and there is already a service entry point, but the issue still needs the non-cancelable exclusion registry and full enforcement path.', 'land the `self_exclusions` persistence layer, expose status/create endpoints, and block contract-entry flows until the exclusion window expires')
engaged(281, '`src/api/database/migrations/020_phase_gamma_trust_chain.sql`, `src/api/src/modules/oracles/`, `src/mobile/services/HealthKitMetadataGuard.spec.ts`, and the blocked-handoff indices for #124/#125/#134', 'Server-side ingestion and validation evidence exists, but the repo still documents the native HealthKit/Health Connect bridge work as blocked on mobile-native capacity.', 'the backend is ahead of the native UI/bridge layer, so this remains dependent on the unresolved iOS/Android engineering lane')
evolving(282, '`src/mobile/screens/ProofCaptureScreen.tsx` (upload progress overlay), `src/mobile/services/UploadService.ts`, and the planning references for `TKT-P1-013`', 'There is already upload/proof plumbing plus a visible progress overlay, so the remaining gap is the full lifecycle state model after the file leaves the device.', 'finish the UI state machine for uploading/processing/verified/failed, bind it to backend proof status, and make retries/reason codes explicit')
distilled(283, '`docs/legal/legal--skill-based-contest-whitepaper.md`, `docs/legal/legal--cross-jurisdictional-consent-matrix.md`, `docs/legal/legal--app-store-ugc-moderation-packet.md`, and the legal appendices', 'This tracker already has several artifact-producing children represented in the repo, while the true human-gated residues are counsel retention and sign-off.', 'keep the tracker as the legal dependency map that separates draftable artifacts from real counsel gates')
evolving(284, '`src/api/src/modules/fury/fury.controller.ts`, `src/api/src/modules/proofs/proofs.service.ts`, and schema fields like `masked_media_uri` / `redaction_status`', 'The backend masking path and reviewer-safe media selection are already partially wired, so the unresolved piece is presenting that redacted state cleanly in the reviewer workbench.', 'finish the workbench UI so reviewers only ever see masked assets plus subject aliases, and add tests that raw media can never leak through the UI path')
distilled(285, '`docs/planning/ux-audit.md`, `docs/departments/prd/REGE.md`, and the product planning corpus', 'The product/design lane already has research and governance structure, but the tracker still mixes metrics, interviews, experiments, and enterprise UX into one bucket.', 'keep this issue as the product control surface and make each child artifact name its success metric and evidence source explicitly')
distilled(286, '`docs/operations/monitoring-setup.md`, `docs/operations/backup-recovery.md`, `docs/operations/incident-response.md`, and operations REGE', 'Operations already has real artifacts, so this tracker is most valuable as the place where uptime, backup, load, and credential/deploy work stay coordinated.', 'keep it as the ops dependency board and tie each sub-issue to a proving artifact or drill result')
evolving(287, '`docs/planning/planning--research-ticket-pack--2026-03-04.md`, `src/api/database/migrations/015_cross_lobby_auditing_fields.sql`, and the timeline entries marking core routing done via E2G-20', 'The anti-collusion routing logic appears conceptually ahead of the admin surface.', 'build the cluster-review UI around the existing routing signals so operators can inspect suspicious reviewer networks and drill into evidence safely')
distilled(288, '`docs/marketing/gtm-strategy.md`, `docs/marketing/content-calendar.md`, and GRO REGE artifacts', 'Growth planning already exists, but this department tracker is still useful as the place that distinguishes channel strategy from the executable weekly calendar.', 'keep this open as the umbrella growth board and require each child to name channel, conversion metric, and owner')
evolving(289, '`docs/FEATURE-BACKLOG.md` (`F-FURY-09`), `docs/planning/planning--research-ticket-pack--2026-03-04.md`, and the existing collusion-routing artifacts', 'Detection/planning for collusion is already present; enforcement is the missing half.', 'implement the slashing rule engine, honey-trap simulations, and false-positive appeal path so anti-collusion has teeth instead of being advisory only')
distilled(290, '`docs/finance/unit-economics.md`, `docs/finance/financial-projections.md`, `docs/finance/runway-tracker.md`, and pricing strategy docs', 'Finance already has several core artifacts, so the tracker’s real value is coordination between economics, Stripe go-live, reconciliation, and enterprise pricing.', 'keep this open as the finance umbrella and insist each child names the financial evidence it should produce')
distilled(291, '`docs/customer-success/faq.md`, `docs/customer-success/onboarding-sequence.md`, and CXS REGE', 'Customer-success content already exists, but the tracker still usefully anchors support setup, help content, onboarding, and churn sensing as one operating lane.', 'treat this as the CXS control surface and keep each child grounded in a measurable user-health signal')
evolving(292, '`docs/legal/legal--skill-based-contest-whitepaper.md`, `docs/planning/planning--truth-chain-map--2026-03-09.md`, and the blocked-handoff lineage around `F-LEGAL-05`', 'The whitepaper draft exists, but the repo itself records major drift between draft artifact, counsel sign-off, and a real release gate.', 'turn the whitepaper into a versioned compliance artifact with hash/signature metadata and make deploy eligibility depend on that proof rather than prose references')
distilled(293, '`docs/enterprise/icp.md`, `docs/enterprise/outreach-sequences.md`, `docs/enterprise/security-questionnaire.md`, and B2B REGE', 'Enterprise sales already has real collateral, but the tracker still needs to distinguish “we have docs” from “we have a repeatable pipeline.”', 'keep it as the B2B umbrella issue and tie each child to pipeline stage, buyer persona, and proof artifact')
distilled(294, '`docs/planning/planning--timeline-with-owners--2026-03-06.md`, `docs/planning/planning--monthly-calendar--2026-03-08.md`, and the phase-gate docs', 'There is already a launch timeline in multiple formats.', 'one operational timeline that stays authoritative when dates, owners, or gate definitions move')
evolving(295, '`docs/ops/ops--testflight-release-runbook.md`, `docs/legal/legal--app-store-ugc-moderation-packet.md`, and `docs/checklists/README.md`', 'The repo already documents TestFlight-specific constraints and even calls out missing upload proof.', 'convert those requirements into a bounded checklist with evidence slots for provisioning, build processing, tester access, moderation/reporting, and smoke validation')
evolving(296, '`docs/legal/legal--real-money-activation-brief.md`, `docs/legal/regulatory-risk-register.md`, the state blocklist appendix, and finance/ops planning', 'The real-money pilot gate is mostly specified in prose already.', 'turn it into an executable readiness checklist that proves escrow, KYC, jurisdiction gating, processor posture, and support/incident handling are actually in place')
evolving(297, '`docs/legal/legal--app-store-ugc-moderation-packet.md`, `docs/planning/planning--timeline-with-owners--2026-03-06.md`, and `docs/checklists/README.md`', 'App Store launch requirements are documented, but still live more as narrative than one accountable gate.', 'assemble a public-launch checklist that ties review policy, moderation, legal copy, release ops, and PR packaging to specific evidence artifacts')
evolving(298, '`docs/checklists/README.md`, `docs/enterprise/security-questionnaire.md`, `docs/enterprise/icp.md`, and the B2B artifacts', 'The enterprise-sales gate is conceptually present, but it still needs a sharp “ready/not ready” contract.', 'define the minimal enterprise trust package—security questionnaire, SLA/DPA posture, ICP clarity, outreach motion, and first-call materials—before calling this lane ready')
distilled(299, '`docs/planning/planning--timeline-with-owners--2026-03-06.md`, `docs/planning/planning--monthly-calendar--2026-03-08.md`, and the cross-department roadmaps', 'Hiring assumptions are scattered across product/legal/ops timelines rather than held in one staffing model.', 'one scenario-based hiring timeline that explicitly names which blockers are “need a person” vs “need clearer sequencing”')
distilled(300, '`docs/marketing/gtm-strategy.md`, `docs/marketing/seo-strategy.md`, and the 30-day GTM planning docs', 'A GTM strategy already exists, so this issue is now about keeping audience, channels, funnel, and launch sequencing coherent.', 'one maintained GTM owner doc that points to the calendar, SEO plan, and funnel implementation evidence')
distilled(301, '`docs/finance/unit-economics.md`, `docs/finance/runway-tracker.md`, `docs/finance/financial-projections.md`, and the metrics trackers in planning', 'KPIs and economics already appear in several documents, which increases the risk of silent drift.', 'a single dashboard spec that defines formulas, source of truth, and review cadence for MRR/CAC/LTV/retention metrics')
distilled(302, '`docs/operations/incident-response.md`, `docs/operations/monitoring-setup.md`, and ops REGE', 'The runbook/playbook work is real, but it should stay grounded in actual monitors and escalation surfaces.', 'one operations contract that joins severity rules, alert routing, rollback steps, and postmortem evidence expectations')
distilled(303, '`docs/departments/prd/REGE.md`, `docs/marketing/gtm-strategy.md`, `docs/enterprise/icp.md`, and the planning corpus', 'Experimentation is referenced in multiple places, but I do not see one clean canonical A/B and user-research framework artifact.', 'a single experiment/research contract covering hypothesis format, metrics, sample rules, and interview handling')
distilled(304, '`docs/marketing/gtm-strategy.md`, `docs/marketing/content-calendar.md`, and `docs/marketing/seo-strategy.md`', 'Marketing execution artifacts already exist, but they are more powerful when treated as one linked system instead of separate prose islands.', 'a single orchestration layer tying narrative, calendar, SEO demand capture, and launch PR moments together')
distilled(305, '`docs/enterprise/security-questionnaire.md`, `docs/enterprise/README.md`, and the enterprise planning material', 'The enterprise trust lane is partially represented by the security questionnaire, but the repo still lacks a clearly named SLA template and DPA/SLA packaging story.', 'a buyer-facing enterprise trust pack that makes posture, promises, and gaps explicit instead of inferred')

# 306-314 feature cluster

evolving(306, '`docs/FEATURE-BACKLOG.md` (`F-AEGIS-04`) and the related recovery planning artifacts', 'Recovery guardrails are explicitly marked `PARTIAL`, which is honest and useful.', 'turn the remaining partial into a precise rule set: danger-zone detection, cooldowns/timelocks, partner escalation, and UI copy that matches the safety model')
evolving(307, '`src/api/src/modules/notifications/notifications.service.ts` and `src/api/src/modules/contracts/attestation.scheduler.ts`', 'RAIN already shows up in notification and scheduler code, so this feature is beyond idea stage.', 'complete the triggering policy, user-facing copy, and tests so the intercession is intentional product behavior rather than a comment-backed hook')
evolving(308, '`docs/FEATURE-BACKLOG.md` (`F-AEGIS-09`) and the contracts/customer-success planning around churn signals', 'The concept is named, but I do not see a finished detection pipeline yet.', 'define the measurable Ostrich pattern, surface it to CXS/notifications, and prove intervention timing with tests or simulations')
evolving(309, '`docs/planning/planning--timeline-with-owners--2026-03-06.md` and `docs/planning/planning--monthly-calendar--2026-03-08.md`', 'This incentive is still described in planning rather than implemented code.', 'pin down the exact economic rule (when the stake doubles, caps, disclosures, and reversal conditions) before it migrates into settlement logic')
evolving(310, '`docs/FEATURE-BACKLOG.md` (`F-LEGAL-03`), the jurisdiction-ticket lineage (`TKT-P0-004`, `TKT-P0-011`), and legal/compliance docs', 'State-specific compliance logic is already acknowledged as partially covered, but the operator-facing toggle surface is still under-specified.', 'make the UI a projection of the actual jurisdiction policy engine so admins cannot drift the display away from enforcement reality')
evolving(312, '`src/web/app/hr/page.tsx`, `src/web/services/api-client.ts` enterprise calls, and `docs/FEATURE-BACKLOG.md` (`F-WEB-03`)', 'There is already an HR route and enterprise metrics/billing client surface, but the backlog explicitly says role-based and org-scoped authz is the gap.', 'finish authorization boundaries first, then widen the dashboard surface only after org isolation is provably enforced')
evolving(313, '`src/desktop/src/components/HashCollider.tsx`, `src/desktop/src/components/hash-collider.utils.ts`, and `docs/FEATURE-BACKLOG.md` (`F-DESKTOP-04`)', 'The desktop hash-collider tool already exists in component form, so this is now a wiring/completeness question, not a concept pitch.', 'finish the end-to-end operator workflow: data source hookup, review ergonomics, and proof that suspected duplicates can be acted on from the desktop surface')
evolving(314, '`src/desktop/src/components/B2BOrchestration.tsx`, `src/desktop/src/services/api.ts`, and `docs/FEATURE-BACKLOG.md` (`F-DESKTOP-05`)', 'There is already a B2B orchestration panel capable of key generation/revocation, and the backlog calls out the remaining gap plainly.', 'add billing-plan controls plus per-key scope restrictions so the panel matches the promised enterprise control surface')

# 315-340 sub-issue cluster

engaged(315, '`docs/legal/appendices/appendix-e--counsel-submission-checklist.md` and the wider legal packet', 'The repo can prepare the packet, but “retain outside legal counsel” is still a real human/business gate rather than an automation problem.', 'the legal artifacts can support the retainer conversation, but the actual retention act remains external to the repo')
engaged(316, '`docs/legal/legal--real-money-activation-brief.md`, `appendix-a--fbo-architecture-diagram.md`, and `appendix-b--terms-of-service-aegis-markup.md`', 'The custody model is documented in enough detail to review, but the sign-off itself still requires an actual lawyer.', 'the repo can sharpen the review packet, yet the authoritative approval must come from counsel outside this codebase')
engaged(317, '`docs/legal/legal--50-state-skill-contest-survey.md`, `appendix-d--state-blocklist-justification-table.md`, and the jurisdiction planning docs', 'The state matrix material exists, but the issue’s core ask is legal confirmation, not internal speculation.', 'the remaining step is counsel validation of the operating-state matrix, which is external and substantive')
distilled(318, '`docs/legal/legal--skill-based-contest-whitepaper.md`, `docs/legal/legal--performance-wagering.md`, and the counsel checklist appendix', 'A whitepaper draft is already present; the missing part is moving from draft argument to reviewable legal packet with versioning and explicit open questions.', 'treat this as the bridge between draft artifact and counsel sign-off rather than a blank writing task')
distilled(319, '`docs/legal/legal--app-store-ugc-moderation-packet.md` and `docs/legal/legal--app-review-notes--phase1-beta.md`', 'The moderation policy document is already substantive.', 'keep this issue alive as the place that converts the packet into an approval-ready checklist with evidence of report/appeal/response mechanics')
distilled(320, '`docs/legal/legal--cross-jurisdictional-consent-matrix.md`', 'The consent matrix already has a durable home.', 'use this issue to keep the matrix aligned with actual data flows, state classes, and user-facing disclosures')
engaged(321, '`docs/FEATURE-BACKLOG.md` (`F-FURY-09`), legal/compliance docs, and the collusion-enforcement planning material', 'I found policy-adjacent material, but not a clearly canonical standalone reviewer-sanctions-and-appeals policy artifact.', 'the issue still needs a dedicated rights/process document before enforcement can be called principled')
engaged(322, '`docs/legal/legal--founder-agreement-draft.md`, `docs/legal/ip-assignment.md`, and enterprise/legal materials', 'There is adjacent legal structure, but I did not surface a crisp partner-authority disclosure review artifact by this exact name.', 'authority/representation boundaries still need an explicit review surface rather than assumption by proximity')
engaged(323, '`docs/enterprise/security-questionnaire.md`, `docs/FEATURE-BACKLOG.md`, and the timeline references to SOC 2', 'The repo is honest that SOC 2 is planned rather than complete.', 'initiating a real audit depends on organizational/vendor work outside the repo, even though the evidence packet can be improved here')
engaged(324, '`docs/departments/README.md` (L4 exists as a named artifact) and the current enterprise/legal docs', 'The repo names DPA as an expected legal artifact, but I did not find a finished DPA template itself.', 'the need is still real and not yet satisfied by the surrounding security/compliance prose')
engaged(325, '`docs/legal/legal--compliance-guardrails.md`, `docs/FEATURE-BACKLOG.md`, and the planning references to prize indemnity', 'Prize indemnity is discussed, but mostly as requirement/strategy rather than as a broker-ready evaluation artifact.', 'the actual insurance evaluation still needs to be turned into a concrete requirements/options memo')
distilled(326, '`docs/marketing/gtm-strategy.md` (already names targets like NPS) plus the PRD planning timeline', 'Beta-success metrics are already referenced in several places, but not yet cleanly normalized into one product-governing metric contract.', 'one short metric sheet for activation, completion, retention, and NPS with explicit thresholds')
distilled(328, '`docs/departments/prd/REGE.md`, `docs/planning/user-personas.md`, and the planning timeline', 'The repo knows interviews matter, but I do not see one canonical 10-user interview protocol artifact yet.', 'a repeatable interview guide that specifies recruiting mix, questions, note schema, and synthesis method')
distilled(329, '`docs/marketing/gtm-strategy.md`, `docs/departments/prd/REGE.md`, and the planning timeline', 'A/B testing is mentioned in multiple places, but the onboarding-variant experiment itself still wants a crisp protocol.', 'a test brief with hypothesis, variants, success metric, stop rule, and copy-review guardrails')
distilled(330, '`docs/departments/prd/REGE.md` (feature prioritization flow) and `docs/planning/feature-matrix.md`', 'Backlog prioritization thinking exists, but the analytics-to-priority handoff still needs an explicit artifact.', 'a prioritization rubric that weights activation, retention, revenue, and implementation cost against real usage signals')
engaged(331, '`src/web/app/hr/`, enterprise artifacts, and the planning timeline', 'The future enterprise surfaces are partially visible, but I did not find a completed enterprise UX audit artifact yet.', 'the issue still needs a real audit once those HR/coach flows are stable enough to review')
distilled(332, '`docs/operations/monitoring-setup.md`', 'Monitoring setup already has a durable doc home.', 'keeping the monitor list, alert thresholds, and ownership current with the actual production surfaces')
distilled(333, '`render.yaml`, `docs/activation/activation-ledger--peer-audited--2026-06-11.md`, and operations planning', 'There is already enough deployment context to evaluate the starter-tier story.', 'a crisp upgrade decision record tying traffic/load/cold-start evidence to plan choice and spend impact')
distilled(334, '`docs/operations/backup-recovery.md`', 'The backup policy has a real artifact already.', 'ensuring the document remains tied to a tested restore drill and not just backup intent')
distilled(335, '`docs/operations/incident-response.md`', 'An incident runbook exists in substance.', 'keeping the severity matrix, escalation tree, and rollback drills tied to live operational reality')
evolving(336, '`docs/architecture/load-test-report.md`, the operations planning docs, and the timeline entry for 500 concurrent users', 'There is already load-test thinking in the repo, but the gate needs reproducible 500-user evidence rather than just aspiration.', 'define the exact scenario mix, pass/fail SLOs, and artifact format for the 500-user simulation')
evolving(337, '`README.md` (Cloudflare/WAF called out), `terraform/`, and the operations/legal planning material', 'WAF/CDN concerns are acknowledged in infrastructure docs, but I do not see a single verification artifact proving the production config is correct.', 'produce a verification checklist that covers cache, headers, bot/rate rules, geo boundaries, and bypass protection')
engaged(338, '`docs/FEATURE-BACKLOG.md` plus the planning references to `TKT-P1-006` and APNs/FCM provisioning', 'The repo is explicit that remote push is blocked on Apple/Google credentials and release-ops work.', 'credential management here is not just a code task; it depends on external key material and secure operational handling')
evolving(339, '`docs/architecture/load-test-report.md` and the Omega timeline entries for 5,000 users', 'The scale-up ask is a real second-order gate beyond the 500-user drill.', 'define the higher-scale scenario, cost envelope, and degradation thresholds before treating this as “just rerun the smaller test bigger”')
engaged(340, '`render.yaml`, the ops timeline, and finance/ops planning', 'Auto-scaling and cost alerting are named, but I do not see a complete, repo-owned configuration proof yet.', 'the issue still needs the concrete monitor/threshold implementation plus agreement on what spend levels should trigger action')

# 341-349 marketing/finance execution

distilled(341, '`docs/marketing/gtm-strategy.md`, `docs/planning/planning--30-day-gtm-strike-plan--2026-03-10.md`, and `docs/planning/planning--jessica-metrics-tracker--2026-06-01.md`', 'Audience/channel mapping already exists in strategy and strike-plan form.', 'one maintained channel map that links each source to message, asset, qualification criteria, and owner')
distilled(342, '`docs/planning/planning--phase1-copy-pack--2026-03-10.md`, `docs/marketing/gtm-strategy.md`, and waitlist/funnel references across planning docs', 'The repo already describes the funnel and some copy assets.', 'a single landing-page funnel spec that ties copy, qualification fields, source attribution, and admit logic together')
distilled(343, '`docs/planning/planning--30-day-social-cadence-calendar--2026-03-10.md`, `planning--jessica-30-day-content-calendar--2026-06-01.md`, and GRO REGE', 'The social/content operating system is already more than an idea.', 'keep this issue as the place where cadence, channel boundaries, and voice/approval rules are reconciled')
distilled(344, '`docs/marketing/seo-strategy.md`, `docs/marketing/content-calendar.md`, and the no-contact GTM docs', 'Demand capture work already has a strategy home.', 'tie keyword clusters to the first publishable articles and the exact conversion events they should feed')
distilled(345, '`docs/marketing/gtm-strategy.md`, `docs/enterprise/outreach-sequences.md`, `docs/customer-success/onboarding-sequence.md`, and the referral references in planning', 'Referral mechanics are already discussed from both consumer and practitioner angles.', 'one operating spec for referral eligibility, reward logic, waitlist/cohort flow, and abuse controls')
engaged(346, '`docs/marketing/README.md` (PR plan is named), App Store launch planning docs, and the current marketing corpus', 'I found launch-adjacent planning, but not a clearly canonical press-kit/target-list/narrative artifact by this exact scope.', 'the PR lane still needs a single operational packet rather than scattered mentions across timeline docs')
distilled(347, '`docs/enterprise/outreach-sequences.md`, `docs/enterprise/icp.md`, and the practitioner-outreach planning references', 'Practitioner outreach already has meaningful raw material.', 'keep this issue focused on turning the sequences and ICP into a first-15-target execution loop with response tracking')
distilled(348, '`docs/finance/unit-economics.md`, `docs/finance/pricing-strategy.md`, and `docs/finance/financial-projections.md`', 'The underlying model exists already.', 'use this issue to keep the $39 contract story numerically consistent across fee split, break-even math, and growth assumptions')
engaged(349, '`README.md` env/deploy contract, `render.yaml`, finance/legal docs, and the real-money activation materials', 'The repo documents how production Stripe would fit, but “switch the account to real money” is still a real operational/business gate.', 'this cannot be honestly marked done from code alone because the decisive step is external account configuration and approval')

assert len(entries) == 108, len(entries)
Path('peer_audit_comments_226_349.json').write_text(json.dumps(entries, indent=2))
print('wrote', len(entries), 'entries')
