#!/usr/bin/env python3
"""derive-domain-streams — the operator's LIFE/WORK DOMAINS are session streams; derive them.

THE DEFECT THIS CLOSES (the third wrong altitude)
    "What session streams do I open? (~6-10)" was answered wrongly twice by this registry: first
    with hand-authored governance phases (s0-s10 — engineering plumbing), then with collaborator
    lanes (one domain's interior). The operator's 2026-07-30 correction: the streams are LIFE/WORK
    DOMAINS — "we have a domain for email, a domain for communication… a domain for finance and
    job applications" — and the collaborator projects are contained WITHIN one of those domains
    (consulting). The excavation across every AI app, disk, and remote (session
    2026-07-30) found the roster already canonical in code since 2026-07-02:
    `cli/src/limen/workstream.py::derived_channels()` — meta process lanes plus one channel per
    organ pillar, with the operator's own vocabulary as aliases (email→correspondence,
    money→financial, job applications→representation). The launcher registry simply never grew a
    family for it. This generator is that family.

WHAT IS DERIVED, FROM WHAT
    Input:  the channel roster (workstream.py meta channels + organ-ladder.json pillars),
            loaded by file path so no package install is required. Deliberately NOT tasks.yaml —
            the board is a live projection that changes every beat; deriving committed rows from
            it would turn parity into a permanently red check. Cartridges point at the board BY
            COMMAND instead.
    Output: (1) the marked block in session-streams.yaml (one `family: domain` row per openable
            channel, carrying `open_rank` — the domain twin of the constellation family's
            `register_tier`: the launcher's RAM bound opens the FIRST N rows, so order IS
            priority), (2) docs/continuations/<channel>/intent.md per derived row, and (3) the
            REMOVAL of any generator-owned cartridge no longer derived — a stale projection is
            drift exactly like a hand-edited one.

WHICH CHANNELS BECOME ROWS (policy constants below, with provenance)
    The SET is the roster — a new organ pillar in organ-ladder.json IS a new domain row with no
    edit here (the "never need him to speak again" property). Three policy constants shape the
    projection, each a decision recorded once:
      OPEN_PRIORITY   the operator-ratified head of the launch order (plan 2026-07-30, inside
                      his stated 6-10) — demand-ordered from the live board at ratification
                      time, frozen here as policy because the board itself may not drive
                      committed bytes.
      ON_DEMAND_META  meta lanes that are openable but never occupy the RAM-bounded head.
      MACHINERY       process/system lanes that get NO launch surface (the T3 analogue).

PUBLIC-SAFE BY CONSTRUCTION
    Everything emitted lands in the public organvm/limen tree. Inputs are code and a committed
    registry (no personal data), and the generator additionally REFUSES to write any output
    matching an email / phone / social-handle pattern — same belt-and-braces as the constellation
    twin, because a future roster edit must not be able to leak through this path.

OPERATOR NOTES SURVIVE
    Each cartridge carries an `<!-- operator-notes:begin -->` … `<!-- operator-notes:end -->`
    region. Regeneration preserves its content verbatim; everything outside it is generator-owned.

Usage:
    derive-domain-streams.py            # dry-run: report what would change, touch nothing
    derive-domain-streams.py --check    # parity: exit 1 iff regeneration would change anything
    derive-domain-streams.py --write    # apply (idempotent; second run changes nothing)
"""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("derive-domain-streams: PyYAML required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

HERE = Path(__file__).resolve().parent
DEFAULT_ROOT = HERE.parents[1]

STREAMS_REL = "institutio/governance/session-streams.yaml"
CARTRIDGE_REL = "docs/continuations/{stream}/intent.md"
ROSTER_REL = "cli/src/limen/workstream.py"
SELF_REL = "institutio/governance/derive-domain-streams.py"

# The marked block this generator owns inside session-streams.yaml. Everything between the
# markers is generated; the rest of the file (hand-authored governance rows, the constellation
# family's own marked block) is never touched.
BEGIN_MARK = (
    "  # ── BEGIN DERIVED: domain streams — generated by "
    "institutio/governance/derive-domain-streams.py; hand-edits are drift (check N) ──"
)
END_MARK = "  # ── END DERIVED: domain streams ──"

NOTES_BEGIN = "<!-- operator-notes:begin -->"
NOTES_END = "<!-- operator-notes:end -->"

# First line of every cartridge this generator writes — how a stale one (a projection whose
# channel no longer derives) is recognized for removal. The constellation generator uses its own
# mark, so the two reaps can never touch each other's cartridges; hand-authored governance
# cartridges carry neither and are never touched.
GENERATED_MARK = "GENERATED by institutio/governance/derive-domain-streams.py"

# ── projection policy (each constant is ONE recorded decision, never re-derived per session) ──
#
# OPEN_PRIORITY — the operator-facing head of the launch order, ratified 2026-07-30 (the plan's
# "9 domains, inside his 6-10"). Order was demand-ranked from the live board at ratification
# (correspondence 43 open tasks · financial 37 · representation active · consulting 64 · legal 39
# · health 10 · education 2 · governance 68 · contributions 101 — the operator-NAMED domains
# lead, the estate lanes follow) and is frozen here because committed bytes may not derive from
# the live board. A channel listed here that leaves the roster simply stops matching — the set
# is always roster ∩ policy.
OPEN_PRIORITY = (
    "correspondence",
    "financial",
    "representation",
    "consulting",
    "legal",
    "health",
    "education",
    "governance",
    "contributions",
)
# Meta process lanes that are openable on demand but never occupy the RAM-bounded head.
ON_DEMAND_META = ("conductor", "substrate")
# Process/system machinery: no launch surface (the constellation family's T3 analogue). A session
# never "opens the prompt-parity domain" — these lanes are served by the beat and the fleet.
MACHINERY = ("prompt-parity", "observation", "sovereignty")

# Belt-and-braces leak guard for everything this script writes into the public tree — same
# patterns as the constellation twin (deliberately shaped to miss dates/SHAs).
LEAK_PATTERNS = (
    ("email address", re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")),
    ("phone number", re.compile(r"(?<![\w-])(?:\+?\d{1,2}[\s.-]?)?(?:\(\d{3}\)|\d{3})[\s.-]\d{3}[\s.-]\d{4}(?![\w-])")),
    ("social handle", re.compile(r"(?<![\w.])@[A-Za-z][A-Za-z0-9_.]{2,}")),
)


def refuse_leaks(text: str, where: str) -> None:
    for label, pat in LEAK_PATTERNS:
        hit = pat.search(text)
        if hit:
            print(
                f"derive-domain-streams: REFUSING to write {where} — output matches a {label} "
                f"pattern ({hit.group(0)[:12]}…). The public tree takes no contact data.",
                file=sys.stderr,
            )
            sys.exit(1)


def _load_roster_module():
    """Load workstream.py by FILE PATH — the same idiom check-session-streams.py uses for the
    tier authority — so the roster is importable without the limen package (or its deps)
    installed. The module guards its model imports for exactly this consumer."""
    path = DEFAULT_ROOT / ROSTER_REL
    spec = importlib.util.spec_from_file_location("_limen_workstream_roster", path)
    if spec is None or spec.loader is None:
        print(f"derive-domain-streams: cannot load roster module at {path}", file=sys.stderr)
        sys.exit(2)
    mod = importlib.util.module_from_spec(spec)
    # Registering before exec is the canonical importlib recipe — and required: the module's
    # @dataclass processing looks itself up in sys.modules (Python ≥3.13 dataclasses._is_type).
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


def load_channels(root: Path) -> list[dict]:
    """The openable domain records, in launch order: OPEN_PRIORITY head (roster ∩ policy), then
    every remaining non-machinery organ channel in roster order (a NEW organ lands here with no
    edit anywhere), then the on-demand meta lanes. `open_rank` is the 1-based position."""
    roster = _load_roster_module().derived_channels(root)
    by_handle = {c.handle: c for c in roster}
    ordered_handles: list[str] = [h for h in OPEN_PRIORITY if h in by_handle]
    for c in roster:
        if c.handle in ordered_handles or c.handle in MACHINERY or c.handle in ON_DEMAND_META:
            continue
        if c.handle in OPEN_PRIORITY:
            continue
        ordered_handles.append(c.handle)
    ordered_handles.extend(h for h in ON_DEMAND_META if h in by_handle)

    records = []
    for rank, handle in enumerate(ordered_handles, 1):
        c = by_handle[handle]
        records.append(
            {
                "handle": handle,
                "rank": rank,
                "source": c.source,
                "title": c.title,
                "detail": (c.detail or "").strip(),
                "aliases": tuple(c.aliases),
                "priority": handle in OPEN_PRIORITY,
                "on_demand": handle in ON_DEMAND_META,
            }
        )
    return records


def max_children(rec: dict) -> int:
    # A domain session coordinates its board channel; 3 bounded children cover drain + verify +
    # one specialist. Consulting is the exception: it contains the whole constellation interior,
    # so it gets the IF-AMALGAMATION cap of 4.
    return 4 if rec["handle"] == "consulting" else 3


def owner_of_record(rec: dict) -> str:
    # The file the channel actually derives from: organ channels exist because organ-ladder.json
    # declares their pillar; meta channels are declared in the roster module itself.
    return "organ-ladder.json" if rec["source"] == "organ" else "cli/src/limen/workstream.py"


def row_title(rec: dict) -> str:
    words = ", ".join(rec["aliases"][:4])
    base = f"{rec['handle']} — the operator's {rec['handle']} domain"
    return f"{base} ({words})" if words else base


def row_note(rec: dict) -> str:
    note = (
        f"Derived from the workstream channel roster ({owner_of_record(rec)}): the operator's "
        f"{rec['handle']} life/work domain. Closes the 2026-07-30 defect — session streams are "
        "life/work domains, and this registry twice shipped without them (governance phases, "
        "then per-project collaborator lanes)."
    )
    if rec["handle"] == "consulting":
        note += " The constellation family is this domain's interior: one stream per collaborator."
    if rec["on_demand"]:
        note += " On-demand meta lane: openable, ranked after every life/work domain."
    return note


def q(s: str) -> str:
    """YAML double-quoted scalar via JSON — one quoting rule, no hand-rolled escaping."""
    return json.dumps(s, ensure_ascii=False)


def stream_block(records: list[dict]) -> str:
    """The generated region of session-streams.yaml, markers included."""
    machinery = ", ".join(MACHINERY)
    out = [BEGIN_MARK]
    out.append("  #")
    out.append("  # These rows are PROJECTIONS of the workstream channel roster (workstream.py meta")
    out.append("  # lanes + one channel per organ-ladder.json pillar) — the operator's LIFE/WORK")
    out.append("  # DOMAINS (2026-07-30: email/comms=correspondence, finance=financial, job")
    out.append("  # applications=representation; collaborator projects live INSIDE consulting).")
    out.append("  # `open_rank` is the launch order — the RAM-bounded launcher opens the first N.")
    out.append(f"  # Machinery lanes get no launch surface: {machinery}.")
    out.append("  # Change the roster (or the policy constants), rerun `derive-domain-streams.py --write`.")
    out.append("")
    for rec in records:
        out.append(f"  {rec['handle']}:")
        out.append("    family: domain")
        # Ordering, not decoration — the domain twin of the constellation family's register_tier:
        # the launcher's RAM bound opens the FIRST N ready rows, so without this field an
        # alphabetical low-demand domain preempts the correspondence/financial head the operator
        # ratified.
        out.append(f"    open_rank: {rec['rank']}")
        out.append(f"    title: {q(row_title(rec))}")
        out.append("    branch_prefix: feat")
        out.append(f"    intent: docs/continuations/{rec['handle']}/intent.md")
        out.append("    requires: []")
        out.append("    unblocks: []")
        out.append("    job_class: synthesis")
        out.append("    predicate: scripts/verify-scoped.sh")
        out.append("    predicate_status: existing")
        out.append("    runway: 8h")
        out.append(f"    owner_of_record: {owner_of_record(rec)}")
        out.append(f"    max_children: {max_children(rec)}")
        out.append(f"    note: {q(row_note(rec))}")
        out.append("")
    if out[-1] == "":
        out.pop()
    out.append(END_MARK)
    return "\n".join(out)


def cartridge(rec: dict, notes_body: str) -> str:
    """One launch cartridge per domain. Derived facts from the roster; board state by COMMAND,
    never by content — the board is live and this file is committed."""
    handle = rec["handle"]
    mc = max_children(rec)
    vocab = ", ".join(rec["aliases"]) if rec["aliases"] else "none — the handle is the word"
    detail = rec["detail"] or "(no channel detail recorded in the roster)"
    consulting_interior = (
        """
## The interior: the collaborator constellation

The collaborator person-streams (`family: constellation`, one stream per T1/T2 person, derived
from `organs/consulting/constellation/registry.yaml`) are THIS domain's interior. Open them with
`limen streams --family constellation` — never duplicate a person's work at this level, and never
open a per-project sibling session (the 2026-07-30 person-unit correction).
"""
        if handle == "consulting"
        else ""
    )
    return f"""<!-- {GENERATED_MARK} — hand-edits outside the
     operator-notes block are drift (check-session-streams.py check N). Change the roster, rerun. -->

# {handle} — the operator's {handle} domain

**family: domain** · open_rank **{rec["rank"]}** · owner of record `{owner_of_record(rec)}`.

Operator vocabulary that resolves here: {vocab}.

Channel: {detail}

## Objective

Drain THIS domain's lane of the board and leave it verifiably further: one worker session draws
open tasks from ONE workstream only (the invariant the channel roster exists to enforce). Claim
work through the broker, advance the highest-pull items, and name each increment in the closeout.
{consulting_interior}
## Evidence, not recall

- Board state: `limen progress --view workstream --scope {handle}` — the board is live; this
  cartridge deliberately embeds none of it.
- Scoped drain: `limen cell conduct <slug> --workstream {handle}` structurally cannot reach
  another domain's work.
- The roster and this row: `python3 institutio/governance/derive-domain-streams.py --check`
  (parity is check N on every pr-gate).

## Fan-out

At most **{mc}** children, only via `limen conduct split <parent_run> --packet`, which reserves
each child against this session's lineage before launch. Never nest a git worktree inside this
one — the reclaim organ sweeps roots, so a nested worktree leaks. Tier every child explicitly.

## Constraints

Fresh branch `feat/{handle}-<increment>` off updated `origin/main`, one concern per branch.
`scripts/verify-scoped.sh` as the push gate; `merge-policy.sh` → `await-pr.sh <PR#> --merge`.
**A domain never settles by trailer** — it is the operator's recurring life/work lane; a
`Settles:` claim is ignored for `family: domain` rows. The domain leaves the launcher only when
the roster changes (an organ pillar removed from `organ-ladder.json`, or the projection policy in
`derive-domain-streams.py` deliberately edited) — then rerun `--write`.

## Done

The session's increments are named per task in the closeout, `scripts/verify-scoped.sh` is green
for the diff, and `python3 scripts/check-session-streams.py` stays OK (checks A-N, including this
family's parity).

{NOTES_BEGIN}
{notes_body}
{NOTES_END}
"""


def existing_notes(path: Path) -> str:
    if not path.exists():
        return ""
    text = path.read_text()
    if NOTES_BEGIN in text and NOTES_END in text:
        return text.split(NOTES_BEGIN, 1)[1].split(NOTES_END, 1)[0].strip("\n")
    return ""


def spliced_streams(root: Path, block: str) -> str:
    current = (root / STREAMS_REL).read_text()
    if BEGIN_MARK in current and END_MARK in current:
        head, rest = current.split(BEGIN_MARK, 1)
        _, tail = rest.split(END_MARK, 1)
        return head + block + tail
    # First run: append the block at end of file (still inside the top-level `streams:` mapping,
    # since every line in the block is indented under it).
    return current.rstrip("\n") + "\n\n" + block + "\n"


def _foreign_ids(root: Path) -> set[str]:
    """Stream ids owned by OTHER families (hand-authored governance rows, the constellation
    block). A channel handle colliding with one would make yaml.safe_load silently keep only the
    last row — so a collision is refused loudly, never merged quietly."""
    current = (root / STREAMS_REL).read_text()
    if BEGIN_MARK in current and END_MARK in current:
        head, rest = current.split(BEGIN_MARK, 1)
        _, tail = rest.split(END_MARK, 1)
        current = head + tail
    try:
        doc = yaml.safe_load(current) or {}
    except yaml.YAMLError:
        return set()
    return set((doc.get("streams") or {}).keys())


def plan(root: Path) -> list[tuple[Path, str, str]]:
    """[(path, current_text, desired_text)] for every file this generator owns.
    A desired text of "" means the file must NOT exist — a stale generator-owned cartridge
    (recognized by GENERATED_MARK) is drift exactly like a hand-edited one."""
    records = load_channels(root)

    clashes = sorted({r["handle"] for r in records} & _foreign_ids(root))
    if clashes:
        print(
            f"derive-domain-streams: REFUSING — channel handle(s) {clashes} already exist as "
            "rows of another family in session-streams.yaml; a duplicate YAML key would silently "
            "shadow one of them. Rename the colliding row's id in its own registry first.",
            file=sys.stderr,
        )
        sys.exit(1)

    changes = []
    streams_path = root / STREAMS_REL
    desired_streams = spliced_streams(root, stream_block(records))
    changes.append((streams_path, streams_path.read_text(), desired_streams))

    wanted = set()
    for rec in records:
        path = root / CARTRIDGE_REL.format(stream=rec["handle"])
        wanted.add(path)
        desired = cartridge(rec, existing_notes(path))
        changes.append((path, path.read_text() if path.exists() else "", desired))

    continuations = root / "docs" / "continuations"
    if continuations.is_dir():
        for path in sorted(continuations.glob("*/intent.md")):
            if path in wanted:
                continue
            text = path.read_text()
            if GENERATED_MARK in text:
                changes.append((path, text, ""))

    for path, _, desired in changes:
        refuse_leaks(desired, str(path.relative_to(root)))
    return changes


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 iff regeneration would change anything")
    mode.add_argument("--write", action="store_true", help="apply the derivation (idempotent)")
    ap.add_argument("--root", type=Path, default=DEFAULT_ROOT, help="repo root (tests point this at a copy)")
    args = ap.parse_args()

    changes = plan(args.root)
    dirty = [(p, cur, des) for p, cur, des in changes if cur != des]

    if not dirty:
        print(f"derive-domain-streams: parity — {len(changes)} derived file(s) all current")
        return 0

    if args.write:
        for path, _, desired in dirty:
            if desired == "":
                path.unlink()
                try:
                    path.parent.rmdir()
                except OSError:
                    pass  # operator files beside the stale cartridge — leave the directory
                print(f"derive-domain-streams: removed stale {path.relative_to(args.root)}")
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(desired)
            print(f"derive-domain-streams: wrote {path.relative_to(args.root)}")
        return 0

    verdict = "DRIFT" if args.check else "would change"
    print(f"derive-domain-streams: {verdict} — {len(dirty)} file(s) differ from derivation:")
    for path, cur, des in dirty:
        rel = str(path.relative_to(args.root))
        print(f"  {rel}")
        for line in list(difflib.unified_diff(cur.splitlines(), des.splitlines(), lineterm="", n=0))[2:8]:
            print(f"    {line}")
    print("fix: change the roster (workstream.py / organ-ladder.json) or the policy constants, then rerun with --write")
    return 1


if __name__ == "__main__":
    sys.exit(main())
