#!/usr/bin/env python3
"""sync-readme.py — render the 4444J99 profile README from provable facts + owned positioning.

The long-planned projector named in face-ownership.json (never implemented until now). It reads the
provability manifest (scripts/profile-visuals.py) + positioning-seeds.json (the owner-approved front
door) + the follow-harvest digest, and writes <out>/README.md. The voice is the owned front door
("production systems, not demos"); the visuals are the self-hosted SVGs; every number is bound to the
manifest. As it emits the systems section it AUGMENTS the manifest with each system's repo-attested
numbers (proven by that repo's own CI), so profile-verify.py can hold the whole page to source.

    python scripts/sync-readme.py --out _profile-build
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _profile as P  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
BIG_NUM = re.compile(r"\b\d{1,3}(?:,\d{3})+\b|\b\d{4,}\b")


def _load_positioning():
    """Import generate-positioning.py (hyphenated) for its value-repo ordering helper."""
    spec = importlib.util.spec_from_file_location(
        "generate_positioning", REPO_ROOT / "scripts" / "generate-positioning.py"
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules["generate_positioning"] = mod
    spec.loader.exec_module(mod)
    return mod


def _stat(manifest: dict, key: str):
    return manifest.get("stats", {}).get(key, {}).get("value")


def _register_repo_numbers(text: str, repo: str, manifest: dict) -> None:
    """Add every big number in `text` to the manifest as repo-attested (proven by that repo's CI)."""
    for m in BIG_NUM.finditer(text):
        raw = m.group(0)
        val = int(raw.replace(",", ""))
        key = f"repo::{repo}::{val}"
        manifest["stats"].setdefault(
            key,
            {
                "value": val,
                "basis": "repo-attested-ci",
                "source_query": f"github.com/{repo} — from the repository's own test/build output ({raw})",
                "attest": "repo",
            },
        )


def _is_placeholder(seed: dict) -> bool:
    """A seed we must not publish: unfinished prose or awaiting-visibility proof signals."""
    blob = str(seed.get("what_it_is", "")) + " " + " ".join(str(s) for s in seed.get("proof_signals", []))
    return bool(re.search(r"\[(pending|awaiting|todo|tbd)\b", blob, re.IGNORECASE))


def render_readme(
    manifest: dict, seeds: dict, digest: dict | None, value_order: list[str], public_set: set[str]
) -> str:
    fd = seeds.get("frontdoor", {})
    repos = seeds.get("repos", {})
    contact = fd.get("contact")
    name = manifest.get("display_name") or "4444J99"
    repos_pub = P._fmt(_stat(manifest, "ecosystem_public_repos"))
    repos_orig = P._fmt(_stat(manifest, "ecosystem_original_repos"))
    contribs = P._fmt(_stat(manifest, "contributions_last_year"))
    since = _stat(manifest, "member_since")
    # the subhead ends with a "Two doors:" lead-in meant for the front-door context; drop it here
    subhead = re.sub(r"\s*Two doors:\s*$", "", str(fd.get("subhead", "")).strip())

    L: list[str] = []
    L.append("<!-- Generated by organvm/limen · scripts/sync-readme.py — DO NOT EDIT BY HAND. -->")
    L.append("<!-- Every number is re-derivable from ./assets/stats-manifest.json. -->")
    L.append("")
    # Left-aligned, seamless: no centering box, no bordered cards — the type hierarchy and the
    # borderless SVGs carry the eye. Lean set only (redundant Milestones + badge-chip panels dropped).
    L.append(
        '<img src="./assets/typing-header.svg" alt="I build production systems that solve '
        'expensive problems." width="760" />'
    )
    L.append("")
    L.append(f"# {name} &nbsp;·&nbsp; `@4444J99`")
    L.append("")
    intro = f"**{fd.get('headline', 'I build production systems that solve expensive problems.')}** {subhead}".strip()
    L.append(intro)
    L.append("")
    attribution = (
        f"The work ships under the [**organvm** ecosystem](https://github.com/organvm) I architect — "
        f"**{repos_pub} public repositories** ({repos_orig} original), "
        f"**{contribs} contributions** in the last year."
    )
    if since:
        attribution += f" On GitHub since {since}."
    L.append(attribution)
    L.append("")
    # verified stats + language mix, side by side (borderless — they read as sections, not boxes)
    L.append(
        '<img src="./assets/stats-card.svg" alt="Verified GitHub statistics" width="48%" />'
        "&nbsp;&nbsp;"
        '<img src="./assets/languages.svg" alt="Language mix" width="48%" />'
    )
    L.append("")
    L.append('<img src="./assets/heatmap.svg" alt="Contribution activity, last year" width="100%" />')
    L.append("")

    # --- the systems (owner-approved order; numbers are each repo's own CI) ---
    L.append("## The systems")
    L.append("")
    L.append(
        "Each is a working production system — source, tests, and live deploy. The numbers are "
        "the repository's own CI output, not adjectives."
    )
    L.append("")
    # list a system only if its repo is verifiably PUBLIC (link won't 404) and its seed is complete
    candidates = [r for r in value_order if r in repos] or list(repos.keys())
    ordered = [r for r in candidates if (not public_set or r in public_set) and not _is_placeholder(repos[r])]
    for repo in ordered:
        seed = repos[repo]
        name = seed.get("display_name", repo.split("/")[-1])
        what = str(seed.get("what_it_is", "")).strip()
        solves = str(seed.get("expensive_problem", "")).strip()
        signals = [str(s) for s in seed.get("proof_signals", [])]
        L.append(f"### [{name}](https://github.com/{repo})")
        if what:
            L.append(what)
            L.append("")
        if solves:
            # the buyer-recognition line — owned copy from the seed, not invented
            L.append(f"**Solves —** {solves}")
            L.append("")
        if signals:
            L.append(" · ".join(f"`{s}`" for s in signals))
            L.append("")
        # per-system doors (the contextual CTA each system had before the provability pass dropped it)
        ctas = []
        if seed.get("cta_client"):
            ctas.append(_door_link(str(seed["cta_client"]).strip(), contact, f"deploy:{repo}"))
        if seed.get("cta_recruiter"):
            ctas.append(_door_link(str(seed["cta_recruiter"]).strip(), contact, f"hire:{repo}"))
        if ctas:
            L.append("→ " + " &nbsp;·&nbsp; ".join(ctas))
            L.append("")
        _register_repo_numbers(what + " " + solves + " " + " ".join(signals), repo, manifest)

    # --- adapted from the builders I follow ---
    if digest and digest.get("techniques"):
        L.append("## Adapted from the builders I follow")
        L.append("")
        L.append(
            f"I harvested the profile READMEs of **all {digest['following_scanned']} accounts I "
            f"follow** and rebuilt their best techniques as my own self-hosted, no-third-party-widget "
            "versions. The most-adopted signals across my follows:"
        )
        L.append("")
        featured = [t for t in digest["techniques"] if t.get("rendered_asset")][:6]
        for t in featured:
            ex = ", ".join(f"@{e}" for e in t["examples"][:3])
            verb = "uses" if t["count"] == 1 else "use"
            L.append(
                f"- **{t['label']}** — {t['count']} of my follows {verb} it "
                f"({ex}) → my own self-hosted [`{t['rendered_asset']}`](./assets/{t['rendered_asset']})."
            )
        L.append("")
        L.append(
            "_Full ranking: [`assets/follow-harvest-report.md`](./assets/follow-harvest-report.md) "
            "· regenerated weekly._"
        )
        L.append("")

    # --- two doors ---
    dc = fd.get("door_client", {})
    dr = fd.get("door_recruiter", {})
    if dc or dr:
        L.append("## Two doors")
        L.append("")
        if dc:
            L.append(f"**{_door_link(dc.get('label', 'Deploy it for your shop'), contact, 'deploy')}**  ")
            if dc.get("blurb"):
                L.append(f"> {dc['blurb']}")
            L.append("")
        if dr:
            L.append(f"**{_door_link(dr.get('label', 'Work with the builder'), contact, 'hire')}**  ")
            if dr.get("blurb"):
                L.append(f"> {dr['blurb']}")
            L.append("")
        if fd.get("closing"):
            L.append(f"_{fd['closing']}_")
            L.append("")

    # --- provability seal ---
    L.append("---")
    L.append(
        f"<sub>Every number on this page is regenerated from the live GitHub API and re-derivable "
        f'from <a href="./assets/stats-manifest.json">stats-manifest.json</a> '
        f"(api-attested = re-run the query; repo-attested = the repo's own CI). "
        f"Visuals are self-hosted SVGs rendered by "
        f'<a href="https://github.com/organvm/limen">organvm/limen</a> — no third-party widgets. '
        f"Generated {manifest.get('generated', '')}.</sub>"
    )
    L.append("")
    return "\n".join(L)


def _door_link(label: str, contact: str | None, door: str) -> str:
    if not contact:
        return label
    from urllib.parse import quote

    subj = quote(f"[front door · {door}] — inbound")
    return f"[{label}](mailto:{contact}?subject={subj})"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render the profile README from manifest + positioning.")
    ap.add_argument("--out", default=os.environ.get("LIMEN_PROFILE_OUT", "_profile-build"))
    ap.add_argument("--seeds", type=Path, default=REPO_ROOT / "positioning-seeds.json")
    ap.add_argument("--value-repos", type=Path, default=REPO_ROOT / "value-repos.json")
    args = ap.parse_args(argv)

    out = Path(args.out)
    assets = out / "assets"
    manifest_path = assets / "stats-manifest.json"
    if not manifest_path.exists():
        print(f"sync-readme: missing {manifest_path} — run profile-visuals.py first", file=sys.stderr)
        return 2

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    seeds = json.loads(args.seeds.read_text(encoding="utf-8"))
    digest_path = assets / "follow-harvest-digest.json"
    digest = json.loads(digest_path.read_text(encoding="utf-8")) if digest_path.exists() else None

    gp = _load_positioning()
    value_order = gp._value_repos(args.value_repos) if args.value_repos.exists() else []

    public_index = assets / "public-repos.json"
    public_set = set()
    if public_index.exists():
        public_set = set(json.loads(public_index.read_text(encoding="utf-8")).get("public_repos", []))

    readme = render_readme(manifest, seeds, digest, value_order, public_set)
    (out / "README.md").write_text(readme, encoding="utf-8")
    # rewrite the manifest with the repo-attested numbers we just emitted
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(
        f"sync-readme: wrote {out / 'README.md'} ({len(readme)} chars); "
        f"manifest now {len(manifest['stats'])} stats "
        f"({sum(1 for s in manifest['stats'].values() if s['attest'] == 'repo')} repo-attested)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
