#!/usr/bin/env python3
"""derive-streams — the constellation PEOPLE are session streams; derive them, never author them.

THE DEFECT THIS CLOSES (twice over)
    The operator's workstreams — the collaborator domains he accepted into tiers on 2026-07-22 —
    live in `organs/consulting/constellation/registry.yaml`. The session-stream registry
    (`institutio/governance/session-streams.yaml`) was authored FRESH on 2026-07-29 without them,
    so "what streams do I open?" answered with internal governance plumbing while the domains the
    operator actually meant were unopenable. Asked for the streams discussed last week, the estate
    quoted a registry invented that morning.

    The first repair derived from the right register at the WRONG GRANULARITY: one stream per
    project, so "open my streams" opened fitness + hokage-chess + micro-tato — three sibling
    sessions all inside rob's one domain (corrected 2026-07-30). A stream is a PERSON's whole
    collaboration; the operator's own count ("6-10") is the T1/T2 people count, and 11 project
    rows where one person is four of them failed the suspicious-count self-check on its face.

    The root rule is *route every new artifact through an existing canonical surface*: the
    register stays the single owner; this script DERIVES one stream row + one launch cartridge
    per T1/T2 PERSON, every one of their lanes carried inside that single cartridge. Nothing here
    is authored twice: a hand-edit to a derived row or cartridge is DRIFT, caught by
    `check-session-streams.py` check M (which runs `--check` on every pr-gate).

WHAT IS DERIVED, FROM WHAT
    Input:  registry.yaml ONLY. Deliberately not tasks.yaml — the board is a live projection that
            changes every beat, and deriving committed files from it would turn parity into a
            permanently red check. Cartridges point at the board BY COMMAND instead.
    Output: (1) the marked block in session-streams.yaml (one `family: constellation` row per
            T1/T2 PERSON; T3 is protocol-first by operator decision and is never given a launch
            surface), (2) docs/continuations/<slug>/intent.md per derived domain, and (3) the
            REMOVAL of any generator-owned cartridge no longer derived — a stale projection
            (e.g. the old per-project ones) is drift exactly like a hand-edited one.

PUBLIC-SAFE BY CONSTRUCTION
    Everything emitted lands in the public organvm/limen tree. Inputs are already the register's
    PUBLIC-SAFE HALF (first-name slugs only), and the generator additionally REFUSES to write any
    output matching an email / phone / social-handle pattern — belt and braces, because a future
    register edit must not be able to leak through this path. Corpus material (atom statement
    text, brainstorm dossiers) is NEVER embedded: cartridges instruct the session to run
    `constellation-dossier.py` locally instead.

OPERATOR NOTES SURVIVE
    Each cartridge carries an `<!-- operator-notes:begin -->` … `<!-- operator-notes:end -->`
    region. Regeneration preserves its content verbatim; everything outside it is generator-owned.

Usage:
    derive-streams.py            # dry-run: report what would change, touch nothing
    derive-streams.py --check    # parity: exit 1 iff regeneration would change anything
    derive-streams.py --write    # apply (idempotent; second run changes nothing)
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("derive-streams: PyYAML required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

HERE = Path(__file__).resolve().parent
DEFAULT_ROOT = HERE.parents[2]

REGISTER_REL = "organs/consulting/constellation/registry.yaml"
STREAMS_REL = "institutio/governance/session-streams.yaml"
CARTRIDGE_REL = "docs/continuations/{stream}/intent.md"
SELF_REL = "organs/consulting/constellation/derive-streams.py"

# First line of every cartridge this generator writes — how a stale one (a projection whose
# stream no longer derives, e.g. the old per-project cartridges) is recognized for removal.
# Hand-authored governance cartridges never carry it and are never touched.
GENERATED_MARK = "GENERATED by organs/consulting/constellation/derive-streams.py"

# The marked block this generator owns inside session-streams.yaml. Everything between the
# markers is generated; the rest of the file (the hand-authored governance rows and their
# commentary) is never touched.
BEGIN_MARK = (
    "  # ── BEGIN DERIVED: constellation lanes — generated by "
    "organs/consulting/constellation/derive-streams.py; hand-edits are drift (check M) ──"
)
END_MARK = "  # ── END DERIVED: constellation lanes ──"

NOTES_BEGIN = "<!-- operator-notes:begin -->"
NOTES_END = "<!-- operator-notes:end -->"

# Lanes the operator accepted for active work. T3 is protocol-first — conversation review before
# any build (registry.yaml tier semantics, operator-accepted 2026-07-22) — so deriving a launch
# surface for it would contradict the register it derives from.
DERIVED_TIERS = ("T1", "T2")

RUNWAY_BY_STAGE = {"live": "8h", "mvp": "8h", "building": "1d", "idea": "1d", "dossier": "1d", "funnelized": "8h"}

OBJECTIVE_BY_STAGE = {
    "idea": (
        "Dossier first. Assemble the evidence from the corpus "
        "(`python3 scripts/constellation-dossier.py --slug {slug} --project {lane}`), then bring a "
        "build/no-build recommendation to the operator's demand review. Do not scaffold a repo "
        "before that review — minting is `scripts/repo-genesis.py`'s job and it is evidence-gated."
    ),
    "dossier": (
        "The dossier exists; sharpen it into a build/no-build recommendation for the operator's "
        "demand review, naming the smallest first build if the answer is build."
    ),
    "building": (
        "Advance the build to its next verifiable rung. Read the repo's own issues/PRs/README for "
        "the current edge; leave the lane one demonstrable increment further with the increment "
        "stated in the closeout."
    ),
    "mvp": (
        "Harden the MVP toward live: close the gap between 'runs for me' and 'runs for {slug}' — "
        "deploy path, onboarding, and the first real-use feedback loop."
    ),
    "live": (
        "The lane is LIVE — operate and grow it; do not rebuild it. Funnel, contract, and "
        "follow-through work only, honoring any register note that closes the build lane."
    ),
    "funnelized": (
        "The funnel is live end-to-end. Optimize conversion and retention; never regress the working shape."
    ),
}

# Belt-and-braces leak guard for everything this script writes into the public tree. The register
# is already public-safe; this stops a future edit from leaking THROUGH the generator. Patterns
# are deliberately shaped to miss dates/SHAs (3-3-4 phone groups, not bare digit runs).
LEAK_PATTERNS = (
    ("email address", re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")),
    ("phone number", re.compile(r"(?<![\w-])(?:\+?\d{1,2}[\s.-]?)?(?:\(\d{3}\)|\d{3})[\s.-]\d{3}[\s.-]\d{4}(?![\w-])")),
    ("social handle", re.compile(r"(?<![\w.])@[A-Za-z][A-Za-z0-9_.]{2,}")),
)


def refuse_leaks(text: str, where: str) -> None:
    for label, pat in LEAK_PATTERNS:
        hit = pat.search(text)
        if hit:
            print(
                f"derive-streams: REFUSING to write {where} — output matches a {label} pattern "
                f"({hit.group(0)[:12]}…). The public tree takes no contact data.",
                file=sys.stderr,
            )
            sys.exit(1)


def load_domains(root: Path) -> list[dict]:
    """One derived record per T1/T2 PERSON — the whole collaboration domain, every lane inside.

    The unit is the person, not the project (corrected 2026-07-30): "open my streams" means one
    session per collaborator domain, never sibling sessions for each of one person's repos. The
    operator's own count for his streams ("6-10") is the T1/T2 people count."""
    register = yaml.safe_load((root / REGISTER_REL).read_text())
    domains = []
    for person in register.get("people", []):
        tier = person.get("tier")
        if tier not in DERIVED_TIERS:
            continue
        lanes = []
        for project in person.get("projects", []):
            repos = [r for r in [project.get("repo"), *project.get("related_repos", [])] if r]
            lanes.append(
                {
                    "lane": project["name"],
                    "stage": project.get("stage", "idea"),
                    "face": project.get("public_face_state", "none"),
                    "repos": repos,
                    "keywords": project.get("keywords", []),
                    "register_notes": project.get("notes"),
                }
            )
        if not lanes:
            continue
        domains.append(
            {
                "slug": person["slug"],
                "tier": tier,
                "lanes": lanes,
                "engagement_ref": person.get("engagement_ref"),
                "funnel_ref": person.get("funnel_instance_ref"),
            }
        )
    domains.sort(key=lambda d: (d["tier"], d["slug"]))
    ids = [d["slug"] for d in domains]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        # A person appearing twice in the register is a register bug to resolve by a human,
        # never an id rule silently invented here.
        print(f"derive-streams: duplicate person slug {sorted(dupes)} — resolve in the register first", file=sys.stderr)
        sys.exit(1)
    return domains


def domain_repos(domain: dict) -> list[str]:
    seen: dict[str, None] = {}
    for lane in domain["lanes"]:
        for repo in lane["repos"]:
            seen.setdefault(repo, None)
    return list(seen)


def max_children(domain: dict) -> int:
    # One child per involved repo plus a coordinator, floored at 2 (an umbrella that cannot split
    # once is not an umbrella) and capped by the IF-AMALGAMATION instinct at 4.
    return min(4, max(2, len(domain_repos(domain)) + 1))


def runway(domain: dict) -> str:
    # The domain's runway is its longest lane's: any lane still pre-build ("1d" class) makes the
    # whole session a "1d" session — a person-domain is one sitting, not per-lane sittings.
    return "1d" if any(RUNWAY_BY_STAGE[lane["stage"]] == "1d" for lane in domain["lanes"]) else "8h"


def row_note(domain: dict) -> str:
    lanes = ", ".join(f"{lane['lane']} (stage {lane['stage']})" for lane in domain["lanes"])
    return (
        f"Derived from the constellation register ({domain['tier']}, tiers operator-accepted "
        f"2026-07-22): {domain['slug']}'s whole collaboration domain — lanes: {lanes}."
    )


def q(s: str) -> str:
    """YAML double-quoted scalar via JSON — one quoting rule, no hand-rolled escaping."""
    return json.dumps(s, ensure_ascii=False)


def stream_block(domains: list[dict]) -> str:
    """The generated region of session-streams.yaml, markers included."""
    out = [BEGIN_MARK]
    out.append("  #")
    out.append("  # These rows are PROJECTIONS of organs/consulting/constellation/registry.yaml —")
    out.append("  # ONE ROW PER T1/T2 PERSON: a stream is a collaborator's whole domain, every one")
    out.append("  # of their lanes inside the one cartridge (T3 is protocol-first and gets no")
    out.append("  # launch surface). Change the register, rerun `derive-streams.py --write`.")
    out.append("")
    for domain in domains:
        n = len(domain["lanes"])
        title = f"{domain['slug']}'s domain ({domain['tier']}, {n} lane{'s' if n != 1 else ''})"
        out.append(f"  {domain['slug']}:")
        out.append("    family: constellation")
        # Ordering, not decoration: T1 is "active demand — build/funnel now" and the launcher's
        # RAM bound opens the FIRST N ready rows, so without this field an alphabetical T2 domain
        # preempts every T1 domain the operator prioritized.
        out.append(f"    register_tier: {domain['tier']}")
        out.append(f"    title: {q(title)}")
        out.append("    branch_prefix: feat")
        out.append(f"    intent: docs/continuations/{domain['slug']}/intent.md")
        out.append("    requires: []")
        out.append("    unblocks: []")
        out.append("    job_class: synthesis")
        out.append("    predicate: organs/consulting/constellation/constellation-done.sh")
        out.append("    predicate_status: existing")
        out.append(f"    runway: {runway(domain)}")
        out.append("    owner_of_record: organs/consulting/constellation/registry.yaml")
        out.append(f"    max_children: {max_children(domain)}")
        out.append(f"    note: {q(row_note(domain))}")
        out.append("")
    if out[-1] == "":
        out.pop()
    out.append(END_MARK)
    return "\n".join(out)


def lane_section(slug: str, lane: dict) -> str:
    objective = OBJECTIVE_BY_STAGE[lane["stage"]].format(slug=slug, lane=lane["lane"])
    repos = "\n".join(f"- `{r}`" for r in lane["repos"]) or "- none minted — evidence gate not yet passed"
    keywords = ", ".join(lane["keywords"])
    register_note = f"\n> Register note: {lane['register_notes']}\n" if lane["register_notes"] else ""
    return f"""### {lane["lane"]} — stage **{lane["stage"]}**, public face **{lane["face"]}**
{register_note}
{objective}

Repos:
{repos}

Keywords: {keywords} · Corpus evidence:
`python3 scripts/constellation-dossier.py --slug {slug} --project {lane["lane"]}`
"""


def cartridge(domain: dict, notes_body: str) -> str:
    """One launch cartridge per PERSON — the whole domain, every lane a section inside it.
    Derived facts from the register; corpus material by COMMAND, never by content — atom
    statement text may not enter the public tree."""
    slug = domain["slug"]
    mc = max_children(domain)
    n = len(domain["lanes"])
    engagement = f"`{domain['engagement_ref']}`" if domain["engagement_ref"] else "none on record"
    funnel = f"`{domain['funnel_ref']}`" if domain["funnel_ref"] else "none"
    lanes = "\n".join(lane_section(slug, lane) for lane in domain["lanes"])
    return f"""<!-- GENERATED by organs/consulting/constellation/derive-streams.py — hand-edits outside the
     operator-notes block are drift (check-session-streams.py check M). Change the register, rerun. -->

# {slug} — collaboration domain

**Tier {domain["tier"]}** (operator-accepted 2026-07-22) · **{n} lane{"s" if n != 1 else ""}** ·
owner of record `organs/consulting/constellation/registry.yaml`.

## Objective

This stream owns {slug}'s WHOLE collaboration — every lane below lives in this one session.
Never open a sibling session for a single lane of this domain. Work the lanes in the order
listed (register order); each lane's stage objective is stated in its section, and the session's
increment is the sum of the lanes it advanced, named per lane in the closeout.

Engagement: {engagement} · Funnel instance: {funnel}

## Lanes (from the register — verify before acting; re-derive, never trust this file's memory)

{lanes}
## Evidence, not recall

- Board state: `limen progress --view workstream --scope consulting` and
  `grep -n "CONST-" tasks.yaml` — the board is live; this cartridge deliberately embeds none of it.
- Dossier commands are per lane, above (dry-run report; `--write` to emit dossier files).
  **Never paste corpus/atom statement text into this repository — it is public.**
- The person context beyond first-name slug lives in the private overlay; reference it by path
  only, never copy content into the public tree.

## Fan-out

At most **{mc}** children, only via `limen conduct split <parent_run> --packet`, which reserves
each child against this session's lineage before launch. Never nest a git worktree inside this
one — the reclaim organ sweeps roots, so a nested worktree leaks. Tier every child explicitly.

## Constraints

Fresh branch `feat/{slug}-<increment>` off updated `origin/main`, one concern per branch.
`scripts/verify-scoped.sh` as the push gate; `merge-policy.sh` → `await-pr.sh <PR#> --merge`.
**A domain never settles by trailer** — it is recurring work you will reopen; a `Settles:` claim
is ignored for constellation rows. The domain leaves the launcher when the OPERATOR re-tiers or
removes the person in `organs/consulting/constellation/registry.yaml` (then rerun
`derive-streams.py --write`). Record a lane's stage change the same way: register first,
derivation follows.

## Done

The objective above is delivered with a verifiable increment named per advanced lane in the
closeout, and `organs/consulting/constellation/constellation-done.sh` plus
`python3 organs/consulting/constellation/validate-constellation.py` stay green. If the register's
stage for any lane changed as a result, update `registry.yaml` and rerun
`python3 organs/consulting/constellation/derive-streams.py --write` in the same branch.

{NOTES_BEGIN}
{notes_body}
{NOTES_END}
"""


def existing_notes(path: Path) -> str:
    if not path.exists():
        return ""
    text = path.read_text()
    if NOTES_BEGIN in text and NOTES_END in text:
        return text.split(NOTES_BEGIN, 1)[1].split(NOTES_END, 1)[0].strip("\n")
    return ""


def spliced_streams(root: Path, block: str) -> str:
    current = (root / STREAMS_REL).read_text()
    if BEGIN_MARK in current and END_MARK in current:
        head, rest = current.split(BEGIN_MARK, 1)
        _, tail = rest.split(END_MARK, 1)
        return head + block + tail
    # First run: append the block at end of file (still inside the top-level `streams:` mapping,
    # since every line in the block is indented under it).
    return current.rstrip("\n") + "\n\n" + block + "\n"


def plan(root: Path) -> list[tuple[Path, str, str]]:
    """[(path, current_text, desired_text)] for every file this generator owns.
    A desired text of "" means the file must NOT exist — a stale generator-owned cartridge
    (recognized by GENERATED_MARK) is drift exactly like a hand-edited one."""
    domains = load_domains(root)
    changes = []

    streams_path = root / STREAMS_REL
    desired_streams = spliced_streams(root, stream_block(domains))
    changes.append((streams_path, streams_path.read_text(), desired_streams))

    wanted = set()
    for domain in domains:
        path = root / CARTRIDGE_REL.format(stream=domain["slug"])
        wanted.add(path)
        desired = cartridge(domain, existing_notes(path))
        changes.append((path, path.read_text() if path.exists() else "", desired))

    continuations = root / "docs" / "continuations"
    if continuations.is_dir():
        for path in sorted(continuations.glob("*/intent.md")):
            if path in wanted:
                continue
            text = path.read_text()
            if GENERATED_MARK in text:
                changes.append((path, text, ""))

    for path, _, desired in changes:
        refuse_leaks(desired, str(path.relative_to(root)))
    return changes


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 iff regeneration would change anything")
    mode.add_argument("--write", action="store_true", help="apply the derivation (idempotent)")
    ap.add_argument("--root", type=Path, default=DEFAULT_ROOT, help="repo root (tests point this at a copy)")
    args = ap.parse_args()

    changes = plan(args.root)
    dirty = [(p, cur, des) for p, cur, des in changes if cur != des]

    if not dirty:
        print(f"derive-streams: parity — {len(changes)} derived file(s) all current")
        return 0

    if args.write:
        for path, _, desired in dirty:
            if desired == "":
                path.unlink()
                try:
                    path.parent.rmdir()
                except OSError:
                    pass  # operator files beside the stale cartridge — leave the directory
                print(f"derive-streams: removed stale {path.relative_to(args.root)}")
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(desired)
            print(f"derive-streams: wrote {path.relative_to(args.root)}")
        return 0

    verdict = "DRIFT" if args.check else "would change"
    print(f"derive-streams: {verdict} — {len(dirty)} file(s) differ from derivation:")
    for path, cur, des in dirty:
        rel = str(path.relative_to(args.root))
        print(f"  {rel}")
        for line in list(difflib.unified_diff(cur.splitlines(), des.splitlines(), lineterm="", n=0))[2:8]:
            print(f"    {line}")
    print("fix: change organs/consulting/constellation/registry.yaml (the owner), then rerun with --write")
    return 1


if __name__ == "__main__":
    sys.exit(main())
