name: Deploy Danse

on:
  push:
    branches:
      - main
    paths:
      - "apps/danse/**"
      - ".github/workflows/deploy-danse.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: danse-deliver
          directory: apps/danse
          githubToken: ${{ secrets.GITHUB_TOKEN }}
